import * as dotenv from 'dotenv';
dotenv.config();
console.log('Test import started');
import { Module } from '@nestjs/common';
console.log('Module imported');
import { CommandFactory } from 'nest-commander';
console.log('CommandFactory imported');
import { PrismaService } from './prisma/prisma.service';
console.log('PrismaService imported');
import { SeedCommand } from './command/seed.command';
console.log('SeedCommand imported');
import { UserRepository } from './common/repository/user/user.repository';
console.log('UserRepository imported');
